from __future__ import annotations

DEMO_SAN_FRANCISCO_FOOD_SPOTS = [
    {
        "id": "sf-la-taqueria",
        "name": "La Taqueria",
        "address": "2889 Mission St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94110",
        "latitude": 37.7509,
        "longitude": -122.4181,
        "stars": 4.6,
        "review_count": 2600,
        "categories": "Mexican, Tacos, Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": False,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual", "lively"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-burma-superstar",
        "name": "Burma Superstar",
        "address": "309 Clement St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94118",
        "latitude": 37.7832,
        "longitude": -122.4627,
        "stars": 4.5,
        "review_count": 7300,
        "categories": "Burmese, Asian Fusion, Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual", "lively"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-zuni-cafe",
        "name": "Zuni Cafe",
        "address": "1658 Market St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94102",
        "latitude": 37.7736,
        "longitude": -122.4216,
        "stars": 4.4,
        "review_count": 3100,
        "categories": "American (New), Mediterranean, Restaurants",
        "price_range": 3,
        "good_for_groups": True,
        "table_service": True,
        "takeout": False,
        "delivery": False,
        "ambiance_labels": ["classic", "date-night", "classy"],
        "attributes": {"RestaurantsPriceRange2": "3"},
    },
    {
        "id": "sf-slanted-door",
        "name": "The Slanted Door",
        "address": "1 Ferry Building",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94111",
        "latitude": 37.7955,
        "longitude": -122.3937,
        "stars": 4.3,
        "review_count": 6100,
        "categories": "Vietnamese, Asian Fusion, Restaurants",
        "price_range": 3,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": False,
        "ambiance_labels": ["upscale", "waterfront", "classy"],
        "attributes": {"RestaurantsPriceRange2": "3"},
    },
    {
        "id": "sf-state-bird",
        "name": "State Bird Provisions",
        "address": "1529 Fillmore St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94115",
        "latitude": 37.7837,
        "longitude": -122.4327,
        "stars": 4.6,
        "review_count": 3200,
        "categories": "American (New), Tapas/Small Plates, Restaurants",
        "price_range": 4,
        "good_for_groups": False,
        "table_service": True,
        "takeout": False,
        "delivery": False,
        "ambiance_labels": ["trendy", "date-night"],
        "attributes": {"RestaurantsPriceRange2": "4"},
    },
    {
        "id": "sf-nopa",
        "name": "Nopa",
        "address": "560 Divisadero St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94117",
        "latitude": 37.7749,
        "longitude": -122.4377,
        "stars": 4.5,
        "review_count": 5600,
        "categories": "American (New), Breakfast & Brunch, Restaurants",
        "price_range": 3,
        "good_for_groups": True,
        "table_service": True,
        "takeout": False,
        "delivery": False,
        "ambiance_labels": ["trendy", "classy"],
        "attributes": {"RestaurantsPriceRange2": "3"},
    },
    {
        "id": "sf-souvla-hayes",
        "name": "Souvla",
        "address": "517 Hayes St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94102",
        "latitude": 37.7764,
        "longitude": -122.4254,
        "stars": 4.4,
        "review_count": 2500,
        "categories": "Greek, Mediterranean, Sandwiches, Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": False,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual", "trendy"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-marufuku",
        "name": "Marufuku Ramen",
        "address": "1581 Webster St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94115",
        "latitude": 37.7855,
        "longitude": -122.4318,
        "stars": 4.5,
        "review_count": 4300,
        "categories": "Japanese, Ramen, Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual", "trendy"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-rintaro",
        "name": "Rintaro",
        "address": "82 14th St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94103",
        "latitude": 37.7684,
        "longitude": -122.4156,
        "stars": 4.6,
        "review_count": 1800,
        "categories": "Japanese, Izakaya, Restaurants",
        "price_range": 3,
        "good_for_groups": False,
        "table_service": True,
        "takeout": False,
        "delivery": False,
        "ambiance_labels": ["romantic", "classy"],
        "attributes": {"RestaurantsPriceRange2": "3"},
    },
    {
        "id": "sf-house-of-nanking",
        "name": "House of Nanking",
        "address": "919 Kearny St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94133",
        "latitude": 37.7966,
        "longitude": -122.4050,
        "stars": 4.2,
        "review_count": 4800,
        "categories": "Chinese, Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual", "touristy"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-farmhouse-thai",
        "name": "Farmhouse Kitchen Thai Cuisine",
        "address": "710 Florida St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94110",
        "latitude": 37.7607,
        "longitude": -122.4114,
        "stars": 4.3,
        "review_count": 3900,
        "categories": "Thai, Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["trendy", "hipster"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-sotto-mare",
        "name": "Sotto Mare",
        "address": "552 Green St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94133",
        "latitude": 37.7998,
        "longitude": -122.4081,
        "stars": 4.6,
        "review_count": 5200,
        "categories": "Seafood, Italian, Restaurants",
        "price_range": 3,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": False,
        "ambiance_labels": ["casual", "touristy"],
        "attributes": {"RestaurantsPriceRange2": "3"},
    },
    {
        "id": "sf-gotts-ferry",
        "name": "Gott's Roadside",
        "address": "1 Ferry Building",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94111",
        "latitude": 37.7955,
        "longitude": -122.3937,
        "stars": 4.2,
        "review_count": 3600,
        "categories": "Burgers, Sandwiches, American (Traditional), Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": False,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual", "touristy"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-la-mediterranee",
        "name": "La Mediterranee",
        "address": "288 Noe St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94114",
        "latitude": 37.7651,
        "longitude": -122.4332,
        "stars": 4.4,
        "review_count": 2100,
        "categories": "Mediterranean, Middle Eastern, Greek, Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual", "romantic"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-flour-water",
        "name": "Flour + Water",
        "address": "2401 Harrison St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94110",
        "latitude": 37.7589,
        "longitude": -122.4126,
        "stars": 4.4,
        "review_count": 2700,
        "categories": "Italian, Pasta Shops, Restaurants",
        "price_range": 3,
        "good_for_groups": False,
        "table_service": True,
        "takeout": False,
        "delivery": False,
        "ambiance_labels": ["romantic", "trendy"],
        "attributes": {"RestaurantsPriceRange2": "3"},
    },
    {
        "id": "sf-cotogna",
        "name": "Cotogna",
        "address": "490 Pacific Ave",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94133",
        "latitude": 37.7974,
        "longitude": -122.4031,
        "stars": 4.5,
        "review_count": 1700,
        "categories": "Italian, Tuscan, Restaurants",
        "price_range": 4,
        "good_for_groups": False,
        "table_service": True,
        "takeout": False,
        "delivery": False,
        "ambiance_labels": ["romantic", "classy"],
        "attributes": {"RestaurantsPriceRange2": "4"},
    },
    {
        "id": "sf-daeho-kalbijjim",
        "name": "Daeho Kalbijjim",
        "address": "1620 Post St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94115",
        "latitude": 37.7858,
        "longitude": -122.4297,
        "stars": 4.5,
        "review_count": 2800,
        "categories": "Korean, Restaurants",
        "price_range": 3,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["trendy", "casual"],
        "attributes": {"RestaurantsPriceRange2": "3"},
    },
    {
        "id": "sf-sweet-maple",
        "name": "Sweet Maple",
        "address": "2101 Sutter St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94115",
        "latitude": 37.7858,
        "longitude": -122.4352,
        "stars": 4.3,
        "review_count": 5100,
        "categories": "Breakfast & Brunch, American (Traditional), Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual", "touristy"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-tartine-bakery",
        "name": "Tartine Bakery",
        "address": "600 Guerrero St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94110",
        "latitude": 37.7615,
        "longitude": -122.4241,
        "stars": 4.5,
        "review_count": 9100,
        "categories": "Bakeries, Desserts, Coffee & Tea, Food",
        "price_range": 2,
        "good_for_groups": False,
        "table_service": False,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual", "touristy"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-bobs-donuts",
        "name": "Bob's Donuts",
        "address": "1621 Polk St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94109",
        "latitude": 37.7915,
        "longitude": -122.4211,
        "stars": 4.6,
        "review_count": 4200,
        "categories": "Donuts, Bakeries, Desserts, Food",
        "price_range": 1,
        "good_for_groups": False,
        "table_service": False,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual"],
        "attributes": {"RestaurantsPriceRange2": "1"},
    },
    {
        "id": "sf-bi-rite-creamery",
        "name": "Bi-Rite Creamery",
        "address": "3692 18th St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94110",
        "latitude": 37.7616,
        "longitude": -122.4257,
        "stars": 4.5,
        "review_count": 6900,
        "categories": "Ice Cream & Frozen Yogurt, Desserts, Food",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": False,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual", "touristy"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-boba-guys-hayes",
        "name": "Boba Guys",
        "address": "8 Octavia St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94102",
        "latitude": 37.7728,
        "longitude": -122.4235,
        "stars": 4.2,
        "review_count": 2400,
        "categories": "Bubble Tea, Coffee & Tea, Desserts, Food",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": False,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual", "trendy"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-philz-mission",
        "name": "Philz Coffee",
        "address": "3101 24th St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94110",
        "latitude": 37.7526,
        "longitude": -122.4133,
        "stars": 4.4,
        "review_count": 2600,
        "categories": "Coffee & Tea, Breakfast & Brunch, Food",
        "price_range": 1,
        "good_for_groups": True,
        "table_service": False,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual", "hipster"],
        "attributes": {"RestaurantsPriceRange2": "1"},
    },
    {
        "id": "sf-swan-oyster-depot",
        "name": "Swan Oyster Depot",
        "address": "1517 Polk St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94109",
        "latitude": 37.7907,
        "longitude": -122.4207,
        "stars": 4.6,
        "review_count": 3300,
        "categories": "Seafood, Seafood Markets, Restaurants",
        "price_range": 3,
        "good_for_groups": False,
        "table_service": True,
        "takeout": True,
        "delivery": False,
        "ambiance_labels": ["casual", "classic"],
        "attributes": {"RestaurantsPriceRange2": "3"},
    },
    {
        "id": "sf-cha-cha-cha",
        "name": "Cha Cha Cha",
        "address": "1801 Haight St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94117",
        "latitude": 37.7690,
        "longitude": -122.4523,
        "stars": 4.2,
        "review_count": 2900,
        "categories": "Caribbean, Cuban, Tapas/Small Plates, Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["lively", "casual"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-senor-sisig",
        "name": "Senor Sisig",
        "address": "990 Valencia St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94110",
        "latitude": 37.7564,
        "longitude": -122.4210,
        "stars": 4.4,
        "review_count": 1800,
        "categories": "Filipino, Mexican, Asian Fusion, Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": False,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual", "trendy"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-shizen",
        "name": "Shizen Vegan Sushi Bar",
        "address": "370 14th St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94103",
        "latitude": 37.7683,
        "longitude": -122.4217,
        "stars": 4.6,
        "review_count": 2500,
        "categories": "Vegan, Vegetarian, Japanese, Sushi Bars, Restaurants",
        "price_range": 3,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["trendy", "classy"],
        "attributes": {"RestaurantsPriceRange2": "3"},
    },
    {
        "id": "sf-mandalay",
        "name": "Mandalay",
        "address": "4348 California St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94118",
        "latitude": 37.7849,
        "longitude": -122.4667,
        "stars": 4.4,
        "review_count": 1600,
        "categories": "Burmese, Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual", "classic"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-club-waziema",
        "name": "Club Waziema",
        "address": "543 Divisadero St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94117",
        "latitude": 37.7747,
        "longitude": -122.4377,
        "stars": 4.3,
        "review_count": 1200,
        "categories": "Ethiopian, African, Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual", "lively"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
]

# Backward-compatible alias for older imports/tests.
DEMO_BAY_AREA_RESTAURANTS = DEMO_SAN_FRANCISCO_FOOD_SPOTS
