from __future__ import annotations

DEMO_BAY_AREA_RESTAURANTS = [{'id': 'demo-la-taqueria',
  'name': 'La Taqueria',
  'address': '2889 Mission St',
  'city': 'San Francisco',
  'state': 'CA',
  'postal_code': '94110',
  'latitude': 37.7509,
  'longitude': -122.4181,
  'stars': 4.6,
  'review_count': 2600,
  'categories': 'Mexican, Tacos, Restaurants',
  'price_range': 2,
  'good_for_groups': True,
  'table_service': False,
  'takeout': True,
  'delivery': True,
  'ambiance_labels': ['casual', 'lively'],
  'attributes': {'RestaurantsPriceRange2': '2'}},
 {'id': 'demo-burma-superstar',
  'name': 'Burma Superstar',
  'address': '309 Clement St',
  'city': 'San Francisco',
  'state': 'CA',
  'postal_code': '94118',
  'latitude': 37.7832,
  'longitude': -122.4627,
  'stars': 4.5,
  'review_count': 7300,
  'categories': 'Burmese, Asian Fusion, Restaurants',
  'price_range': 2,
  'good_for_groups': True,
  'table_service': True,
  'takeout': True,
  'delivery': True,
  'ambiance_labels': ['casual', 'lively'],
  'attributes': {'RestaurantsPriceRange2': '2'}},
 {'id': 'demo-zuni-cafe',
  'name': 'Zuni Cafe',
  'address': '1658 Market St',
  'city': 'San Francisco',
  'state': 'CA',
  'postal_code': '94102',
  'latitude': 37.7736,
  'longitude': -122.4216,
  'stars': 4.4,
  'review_count': 3100,
  'categories': 'American (New), Mediterranean, Restaurants',
  'price_range': 3,
  'good_for_groups': True,
  'table_service': True,
  'takeout': False,
  'delivery': False,
  'ambiance_labels': ['classic', 'date-night'],
  'attributes': {'RestaurantsPriceRange2': '3'}},
 {'id': 'demo-slanted-door',
  'name': 'The Slanted Door',
  'address': '1 Ferry Building',
  'city': 'San Francisco',
  'state': 'CA',
  'postal_code': '94111',
  'latitude': 37.7955,
  'longitude': -122.3937,
  'stars': 4.3,
  'review_count': 6100,
  'categories': 'Vietnamese, Asian Fusion, Restaurants',
  'price_range': 3,
  'good_for_groups': True,
  'table_service': True,
  'takeout': True,
  'delivery': False,
  'ambiance_labels': ['upscale', 'waterfront'],
  'attributes': {'RestaurantsPriceRange2': '3'}},
 {'id': 'demo-cheeseboard',
  'name': 'Cheese Board Pizza',
  'address': '1512 Shattuck Ave',
  'city': 'Berkeley',
  'state': 'CA',
  'postal_code': '94709',
  'latitude': 37.8797,
  'longitude': -122.2698,
  'stars': 4.7,
  'review_count': 5400,
  'categories': 'Pizza, Vegetarian, Restaurants',
  'price_range': 1,
  'good_for_groups': True,
  'table_service': False,
  'takeout': True,
  'delivery': False,
  'ambiance_labels': ['casual', 'outdoor'],
  'attributes': {'RestaurantsPriceRange2': '1'}},
 {'id': 'demo-state-bird',
  'name': 'State Bird Provisions',
  'address': '1529 Fillmore St',
  'city': 'San Francisco',
  'state': 'CA',
  'postal_code': '94115',
  'latitude': 37.7837,
  'longitude': -122.4327,
  'stars': 4.6,
  'review_count': 3200,
  'categories': 'American (New), Tapas/Small Plates, Restaurants',
  'price_range': 4,
  'good_for_groups': False,
  'table_service': True,
  'takeout': False,
  'delivery': False,
  'ambiance_labels': ['trendy', 'date-night'],
  'attributes': {'RestaurantsPriceRange2': '4'}},
 {'id': 'demo-nopa',
  'name': 'Nopa',
  'address': '560 Divisadero St',
  'city': 'San Francisco',
  'state': 'CA',
  'postal_code': '94117',
  'latitude': 37.7749,
  'longitude': -122.4377,
  'stars': 4.5,
  'review_count': 5600,
  'categories': 'American (New), Breakfast & Brunch, Restaurants',
  'price_range': 3,
  'good_for_groups': True,
  'table_service': True,
  'takeout': False,
  'delivery': False,
  'ambiance_labels': ['trendy', 'classy'],
  'attributes': {'RestaurantsPriceRange2': '3'}},
 {'id': 'demo-souvla-hayes',
  'name': 'Souvla',
  'address': '517 Hayes St',
  'city': 'San Francisco',
  'state': 'CA',
  'postal_code': '94102',
  'latitude': 37.7764,
  'longitude': -122.4254,
  'stars': 4.4,
  'review_count': 2500,
  'categories': 'Greek, Mediterranean, Sandwiches, Restaurants',
  'price_range': 2,
  'good_for_groups': True,
  'table_service': False,
  'takeout': True,
  'delivery': True,
  'ambiance_labels': ['casual', 'trendy'],
  'attributes': {'RestaurantsPriceRange2': '2'}},
 {'id': 'demo-marufuku',
  'name': 'Marufuku Ramen',
  'address': '1581 Webster St',
  'city': 'San Francisco',
  'state': 'CA',
  'postal_code': '94115',
  'latitude': 37.7855,
  'longitude': -122.4318,
  'stars': 4.5,
  'review_count': 4300,
  'categories': 'Japanese, Ramen, Restaurants',
  'price_range': 2,
  'good_for_groups': True,
  'table_service': True,
  'takeout': True,
  'delivery': True,
  'ambiance_labels': ['casual', 'trendy'],
  'attributes': {'RestaurantsPriceRange2': '2'}},
 {'id': 'demo-rintaro',
  'name': 'Rintaro',
  'address': '82 14th St',
  'city': 'San Francisco',
  'state': 'CA',
  'postal_code': '94103',
  'latitude': 37.7684,
  'longitude': -122.4156,
  'stars': 4.6,
  'review_count': 1800,
  'categories': 'Japanese, Izakaya, Restaurants',
  'price_range': 3,
  'good_for_groups': False,
  'table_service': True,
  'takeout': False,
  'delivery': False,
  'ambiance_labels': ['romantic', 'classy'],
  'attributes': {'RestaurantsPriceRange2': '3'}},
 {'id': 'demo-viks-chaat',
  'name': "Vik's Chaat",
  'address': '2390 Fourth St',
  'city': 'Berkeley',
  'state': 'CA',
  'postal_code': '94710',
  'latitude': 37.8628,
  'longitude': -122.2984,
  'stars': 4.4,
  'review_count': 2100,
  'categories': 'Indian, Pakistani, Restaurants',
  'price_range': 1,
  'good_for_groups': True,
  'table_service': False,
  'takeout': True,
  'delivery': True,
  'ambiance_labels': ['casual'],
  'attributes': {'RestaurantsPriceRange2': '1'}},
 {'id': 'demo-house-of-nanking',
  'name': 'House of Nanking',
  'address': '919 Kearny St',
  'city': 'San Francisco',
  'state': 'CA',
  'postal_code': '94133',
  'latitude': 37.7966,
  'longitude': -122.405,
  'stars': 4.2,
  'review_count': 4800,
  'categories': 'Chinese, Restaurants',
  'price_range': 2,
  'good_for_groups': True,
  'table_service': True,
  'takeout': True,
  'delivery': True,
  'ambiance_labels': ['casual', 'touristy'],
  'attributes': {'RestaurantsPriceRange2': '2'}},
 {'id': 'demo-farmhouse-thai',
  'name': 'Farmhouse Kitchen Thai Cuisine',
  'address': '710 Florida St',
  'city': 'San Francisco',
  'state': 'CA',
  'postal_code': '94110',
  'latitude': 37.7607,
  'longitude': -122.4114,
  'stars': 4.3,
  'review_count': 3900,
  'categories': 'Thai, Restaurants',
  'price_range': 2,
  'good_for_groups': True,
  'table_service': True,
  'takeout': True,
  'delivery': True,
  'ambiance_labels': ['trendy', 'hipster'],
  'attributes': {'RestaurantsPriceRange2': '2'}},
 {'id': 'demo-sotto-mare',
  'name': 'Sotto Mare',
  'address': '552 Green St',
  'city': 'San Francisco',
  'state': 'CA',
  'postal_code': '94133',
  'latitude': 37.7998,
  'longitude': -122.4081,
  'stars': 4.6,
  'review_count': 5200,
  'categories': 'Seafood, Italian, Restaurants',
  'price_range': 3,
  'good_for_groups': True,
  'table_service': True,
  'takeout': True,
  'delivery': False,
  'ambiance_labels': ['casual', 'touristy'],
  'attributes': {'RestaurantsPriceRange2': '3'}},
 {'id': 'demo-tacos-oscar',
  'name': 'Tacos Oscar',
  'address': '420 40th St',
  'city': 'Oakland',
  'state': 'CA',
  'postal_code': '94609',
  'latitude': 37.8286,
  'longitude': -122.2605,
  'stars': 4.7,
  'review_count': 1000,
  'categories': 'Mexican, Tacos, Vegetarian, Restaurants',
  'price_range': 1,
  'good_for_groups': True,
  'table_service': False,
  'takeout': True,
  'delivery': False,
  'ambiance_labels': ['casual', 'hipster'],
  'attributes': {'RestaurantsPriceRange2': '1'}},
 {'id': 'demo-homeroom',
  'name': 'Homeroom',
  'address': '400 40th St',
  'city': 'Oakland',
  'state': 'CA',
  'postal_code': '94609',
  'latitude': 37.8283,
  'longitude': -122.2603,
  'stars': 4.3,
  'review_count': 3200,
  'categories': 'American (Traditional), Comfort Food, Restaurants',
  'price_range': 2,
  'good_for_groups': True,
  'table_service': True,
  'takeout': True,
  'delivery': True,
  'ambiance_labels': ['casual'],
  'attributes': {'RestaurantsPriceRange2': '2'}},
 {'id': 'demo-gotts-ferry',
  'name': "Gott's Roadside",
  'address': '1 Ferry Building',
  'city': 'San Francisco',
  'state': 'CA',
  'postal_code': '94111',
  'latitude': 37.7955,
  'longitude': -122.3937,
  'stars': 4.2,
  'review_count': 3600,
  'categories': 'Burgers, Sandwiches, American (Traditional), Restaurants',
  'price_range': 2,
  'good_for_groups': True,
  'table_service': False,
  'takeout': True,
  'delivery': True,
  'ambiance_labels': ['casual', 'touristy'],
  'attributes': {'RestaurantsPriceRange2': '2'}},
 {'id': 'demo-la-mediterranee',
  'name': 'La Mediterranee',
  'address': '288 Noe St',
  'city': 'San Francisco',
  'state': 'CA',
  'postal_code': '94114',
  'latitude': 37.7651,
  'longitude': -122.4332,
  'stars': 4.4,
  'review_count': 2100,
  'categories': 'Mediterranean, Middle Eastern, Greek, Restaurants',
  'price_range': 2,
  'good_for_groups': True,
  'table_service': True,
  'takeout': True,
  'delivery': True,
  'ambiance_labels': ['casual', 'romantic'],
  'attributes': {'RestaurantsPriceRange2': '2'}},
 {'id': 'demo-mama-oakland',
  'name': 'Mama Oakland',
  'address': '388 Grand Ave',
  'city': 'Oakland',
  'state': 'CA',
  'postal_code': '94610',
  'latitude': 37.8092,
  'longitude': -122.2533,
  'stars': 4.5,
  'review_count': 900,
  'categories': 'Italian, Pasta Shops, Restaurants',
  'price_range': 3,
  'good_for_groups': False,
  'table_service': True,
  'takeout': False,
  'delivery': False,
  'ambiance_labels': ['romantic', 'classy'],
  'attributes': {'RestaurantsPriceRange2': '3'}},
 {'id': 'demo-flour-water',
  'name': 'Flour + Water',
  'address': '2401 Harrison St',
  'city': 'San Francisco',
  'state': 'CA',
  'postal_code': '94110',
  'latitude': 37.7589,
  'longitude': -122.4126,
  'stars': 4.4,
  'review_count': 2700,
  'categories': 'Italian, Pasta Shops, Restaurants',
  'price_range': 3,
  'good_for_groups': False,
  'table_service': True,
  'takeout': False,
  'delivery': False,
  'ambiance_labels': ['romantic', 'trendy'],
  'attributes': {'RestaurantsPriceRange2': '3'}},
 {'id': 'demo-cotogna',
  'name': 'Cotogna',
  'address': '490 Pacific Ave',
  'city': 'San Francisco',
  'state': 'CA',
  'postal_code': '94133',
  'latitude': 37.7974,
  'longitude': -122.4031,
  'stars': 4.5,
  'review_count': 1700,
  'categories': 'Italian, Tuscan, Restaurants',
  'price_range': 4,
  'good_for_groups': False,
  'table_service': True,
  'takeout': False,
  'delivery': False,
  'ambiance_labels': ['romantic', 'classy'],
  'attributes': {'RestaurantsPriceRange2': '4'}},
 {'id': 'demo-daol-korean',
  'name': 'Daeho Kalbijjim',
  'address': '1620 Post St',
  'city': 'San Francisco',
  'state': 'CA',
  'postal_code': '94115',
  'latitude': 37.7858,
  'longitude': -122.4297,
  'stars': 4.5,
  'review_count': 2800,
  'categories': 'Korean, Restaurants',
  'price_range': 3,
  'good_for_groups': True,
  'table_service': True,
  'takeout': True,
  'delivery': True,
  'ambiance_labels': ['trendy', 'casual'],
  'attributes': {'RestaurantsPriceRange2': '3'}},
 {'id': 'demo-cholita-linda',
  'name': 'Cholita Linda',
  'address': '4923 Telegraph Ave',
  'city': 'Oakland',
  'state': 'CA',
  'postal_code': '94609',
  'latitude': 37.8358,
  'longitude': -122.2632,
  'stars': 4.4,
  'review_count': 2200,
  'categories': 'Latin American, Mexican, Cuban, Sandwiches, Restaurants',
  'price_range': 2,
  'good_for_groups': True,
  'table_service': False,
  'takeout': True,
  'delivery': True,
  'ambiance_labels': ['casual', 'hipster'],
  'attributes': {'RestaurantsPriceRange2': '2'}},
 {'id': 'demo-horn-bbq',
  'name': 'Horn Barbecue',
  'address': '2534 Mandela Pkwy',
  'city': 'Oakland',
  'state': 'CA',
  'postal_code': '94607',
  'latitude': 37.8191,
  'longitude': -122.289,
  'stars': 4.1,
  'review_count': 1600,
  'categories': 'Barbeque, Smokehouse, Restaurants',
  'price_range': 2,
  'good_for_groups': True,
  'table_service': False,
  'takeout': True,
  'delivery': False,
  'ambiance_labels': ['casual'],
  'attributes': {'RestaurantsPriceRange2': '2'}},
 {'id': 'demo-sweet-maple',
  'name': 'Sweet Maple',
  'address': '2101 Sutter St',
  'city': 'San Francisco',
  'state': 'CA',
  'postal_code': '94115',
  'latitude': 37.7858,
  'longitude': -122.4352,
  'stars': 4.3,
  'review_count': 5100,
  'categories': 'Breakfast & Brunch, American (Traditional), Restaurants',
  'price_range': 2,
  'good_for_groups': True,
  'table_service': True,
  'takeout': True,
  'delivery': True,
  'ambiance_labels': ['casual', 'touristy'],
  'attributes': {'RestaurantsPriceRange2': '2'}}]
