from __future__ import annotations

DEMO_SAN_FRANCISCO_FOOD_SPOTS = [
    {
        "id": "sf-la-taqueria",
        "name": "La Taqueria",
        "address": "2889 Mission St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94110",
        "latitude": 37.7509,
        "longitude": -122.4181,
        "stars": 4.6,
        "review_count": 2600,
        "categories": "Mexican, Tacos, Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": False,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual", "lively"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-burma-superstar",
        "name": "Burma Superstar",
        "address": "309 Clement St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94118",
        "latitude": 37.7832,
        "longitude": -122.4627,
        "stars": 4.5,
        "review_count": 7300,
        "categories": "Burmese, Asian Fusion, Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual", "lively"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-zuni-cafe",
        "name": "Zuni Cafe",
        "address": "1658 Market St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94102",
        "latitude": 37.7736,
        "longitude": -122.4216,
        "stars": 4.4,
        "review_count": 3100,
        "categories": "American (New), Mediterranean, Restaurants",
        "price_range": 3,
        "good_for_groups": True,
        "table_service": True,
        "takeout": False,
        "delivery": False,
        "ambiance_labels": ["classic", "date-night", "classy"],
        "attributes": {"RestaurantsPriceRange2": "3"},
    },
    {
        "id": "sf-slanted-door",
        "name": "The Slanted Door",
        "address": "1 Ferry Building",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94111",
        "latitude": 37.7955,
        "longitude": -122.3937,
        "stars": 4.3,
        "review_count": 6100,
        "categories": "Vietnamese, Asian Fusion, Restaurants",
        "price_range": 3,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": False,
        "ambiance_labels": ["upscale", "waterfront", "classy"],
        "attributes": {"RestaurantsPriceRange2": "3"},
    },
    {
        "id": "sf-state-bird",
        "name": "State Bird Provisions",
        "address": "1529 Fillmore St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94115",
        "latitude": 37.7837,
        "longitude": -122.4327,
        "stars": 4.6,
        "review_count": 3200,
        "categories": "American (New), Tapas/Small Plates, Restaurants",
        "price_range": 4,
        "good_for_groups": False,
        "table_service": True,
        "takeout": False,
        "delivery": False,
        "ambiance_labels": ["trendy", "date-night"],
        "attributes": {"RestaurantsPriceRange2": "4"},
    },
    {
        "id": "sf-nopa",
        "name": "Nopa",
        "address": "560 Divisadero St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94117",
        "latitude": 37.7749,
        "longitude": -122.4377,
        "stars": 4.5,
        "review_count": 5600,
        "categories": "American (New), Breakfast & Brunch, Restaurants",
        "price_range": 3,
        "good_for_groups": True,
        "table_service": True,
        "takeout": False,
        "delivery": False,
        "ambiance_labels": ["trendy", "classy"],
        "attributes": {"RestaurantsPriceRange2": "3"},
    },
    {
        "id": "sf-souvla-hayes",
        "name": "Souvla",
        "address": "517 Hayes St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94102",
        "latitude": 37.7764,
        "longitude": -122.4254,
        "stars": 4.4,
        "review_count": 2500,
        "categories": "Greek, Mediterranean, Sandwiches, Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": False,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual", "trendy"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-marufuku",
        "name": "Marufuku Ramen",
        "address": "1581 Webster St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94115",
        "latitude": 37.7855,
        "longitude": -122.4318,
        "stars": 4.5,
        "review_count": 4300,
        "categories": "Japanese, Ramen, Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual", "trendy"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-rintaro",
        "name": "Rintaro",
        "address": "82 14th St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94103",
        "latitude": 37.7684,
        "longitude": -122.4156,
        "stars": 4.6,
        "review_count": 1800,
        "categories": "Japanese, Izakaya, Restaurants",
        "price_range": 3,
        "good_for_groups": False,
        "table_service": True,
        "takeout": False,
        "delivery": False,
        "ambiance_labels": ["romantic", "classy"],
        "attributes": {"RestaurantsPriceRange2": "3"},
    },
    {
        "id": "sf-house-of-nanking",
        "name": "House of Nanking",
        "address": "919 Kearny St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94133",
        "latitude": 37.7966,
        "longitude": -122.4050,
        "stars": 4.2,
        "review_count": 4800,
        "categories": "Chinese, Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual", "touristy"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-farmhouse-thai",
        "name": "Farmhouse Kitchen Thai Cuisine",
        "address": "710 Florida St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94110",
        "latitude": 37.7607,
        "longitude": -122.4114,
        "stars": 4.3,
        "review_count": 3900,
        "categories": "Thai, Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["trendy", "hipster"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-sotto-mare",
        "name": "Sotto Mare",
        "address": "552 Green St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94133",
        "latitude": 37.7998,
        "longitude": -122.4081,
        "stars": 4.6,
        "review_count": 5200,
        "categories": "Seafood, Italian, Restaurants",
        "price_range": 3,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": False,
        "ambiance_labels": ["casual", "touristy"],
        "attributes": {"RestaurantsPriceRange2": "3"},
    },
    {
        "id": "sf-gotts-ferry",
        "name": "Gott's Roadside",
        "address": "1 Ferry Building",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94111",
        "latitude": 37.7955,
        "longitude": -122.3937,
        "stars": 4.2,
        "review_count": 3600,
        "categories": "Burgers, Sandwiches, American (Traditional), Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": False,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual", "touristy"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-la-mediterranee",
        "name": "La Mediterranee",
        "address": "288 Noe St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94114",
        "latitude": 37.7651,
        "longitude": -122.4332,
        "stars": 4.4,
        "review_count": 2100,
        "categories": "Mediterranean, Middle Eastern, Greek, Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual", "romantic"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-flour-water",
        "name": "Flour + Water",
        "address": "2401 Harrison St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94110",
        "latitude": 37.7589,
        "longitude": -122.4126,
        "stars": 4.4,
        "review_count": 2700,
        "categories": "Italian, Pasta Shops, Restaurants",
        "price_range": 3,
        "good_for_groups": False,
        "table_service": True,
        "takeout": False,
        "delivery": False,
        "ambiance_labels": ["romantic", "trendy"],
        "attributes": {"RestaurantsPriceRange2": "3"},
    },
    {
        "id": "sf-cotogna",
        "name": "Cotogna",
        "address": "490 Pacific Ave",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94133",
        "latitude": 37.7974,
        "longitude": -122.4031,
        "stars": 4.5,
        "review_count": 1700,
        "categories": "Italian, Tuscan, Restaurants",
        "price_range": 4,
        "good_for_groups": False,
        "table_service": True,
        "takeout": False,
        "delivery": False,
        "ambiance_labels": ["romantic", "classy"],
        "attributes": {"RestaurantsPriceRange2": "4"},
    },
    {
        "id": "sf-daeho-kalbijjim",
        "name": "Daeho Kalbijjim",
        "address": "1620 Post St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94115",
        "latitude": 37.7858,
        "longitude": -122.4297,
        "stars": 4.5,
        "review_count": 2800,
        "categories": "Korean, Restaurants",
        "price_range": 3,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["trendy", "casual"],
        "attributes": {"RestaurantsPriceRange2": "3"},
    },
    {
        "id": "sf-sweet-maple",
        "name": "Sweet Maple",
        "address": "2101 Sutter St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94115",
        "latitude": 37.7858,
        "longitude": -122.4352,
        "stars": 4.3,
        "review_count": 5100,
        "categories": "Breakfast & Brunch, American (Traditional), Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual", "touristy"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-udupi-palace",
        "name": "Udupi Palace",
        "address": "1007 Valencia St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94110",
        "latitude": 37.7560,
        "longitude": -122.4212,
        "stars": 4.3,
        "review_count": 1700,
        "categories": "Indian, South Indian, Vegetarian, Dosa, Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-kinara",
        "name": "Kinara",
        "address": "937 Geary St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94109",
        "latitude": 37.7861,
        "longitude": -122.4187,
        "stars": 4.4,
        "review_count": 1200,
        "categories": "Indian, Pakistani, Halal, Curry, Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual", "cozy"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-curry-leaf",
        "name": "Curry Leaf",
        "address": "943 Columbus Ave",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94133",
        "latitude": 37.8020,
        "longitude": -122.4137,
        "stars": 4.2,
        "review_count": 950,
        "categories": "Indian, Pakistani, Curry, Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-rooh",
        "name": "Rooh",
        "address": "333 Brannan St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94107",
        "latitude": 37.7809,
        "longitude": -122.3924,
        "stars": 4.3,
        "review_count": 1800,
        "categories": "Indian, Cocktail Bars, Restaurants",
        "price_range": 3,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": False,
        "ambiance_labels": ["trendy", "classy"],
        "attributes": {"RestaurantsPriceRange2": "3"},
    },
    {
        "id": "sf-keeva-indian-kitchen",
        "name": "Keeva Indian Kitchen",
        "address": "908 Clement St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94118",
        "latitude": 37.7825,
        "longitude": -122.4689,
        "stars": 4.5,
        "review_count": 900,
        "categories": "Indian, Himalayan/Nepalese, Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual", "cozy"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-tartine-bakery",
        "name": "Tartine Bakery",
        "address": "600 Guerrero St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94110",
        "latitude": 37.7615,
        "longitude": -122.4241,
        "stars": 4.5,
        "review_count": 9100,
        "categories": "Bakeries, Desserts, Coffee & Tea, Food",
        "price_range": 2,
        "good_for_groups": False,
        "table_service": False,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual", "touristy"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-bobs-donuts",
        "name": "Bob's Donuts",
        "address": "1621 Polk St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94109",
        "latitude": 37.7915,
        "longitude": -122.4211,
        "stars": 4.6,
        "review_count": 4200,
        "categories": "Donuts, Bakeries, Desserts, Food",
        "price_range": 1,
        "good_for_groups": False,
        "table_service": False,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual"],
        "attributes": {"RestaurantsPriceRange2": "1"},
    },
    {
        "id": "sf-bi-rite-creamery",
        "name": "Bi-Rite Creamery",
        "address": "3692 18th St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94110",
        "latitude": 37.7616,
        "longitude": -122.4257,
        "stars": 4.5,
        "review_count": 6900,
        "categories": "Ice Cream & Frozen Yogurt, Desserts, Food",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": False,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual", "touristy"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-boba-guys-hayes",
        "name": "Boba Guys",
        "address": "8 Octavia St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94102",
        "latitude": 37.7728,
        "longitude": -122.4235,
        "stars": 4.2,
        "review_count": 2400,
        "categories": "Bubble Tea, Coffee & Tea, Desserts, Food",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": False,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual", "trendy"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-philz-mission",
        "name": "Philz Coffee",
        "address": "3101 24th St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94110",
        "latitude": 37.7526,
        "longitude": -122.4133,
        "stars": 4.4,
        "review_count": 2600,
        "categories": "Coffee & Tea, Breakfast & Brunch, Food",
        "price_range": 1,
        "good_for_groups": True,
        "table_service": False,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual", "hipster"],
        "attributes": {"RestaurantsPriceRange2": "1"},
    },
    {
        "id": "sf-swan-oyster-depot",
        "name": "Swan Oyster Depot",
        "address": "1517 Polk St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94109",
        "latitude": 37.7907,
        "longitude": -122.4207,
        "stars": 4.6,
        "review_count": 3300,
        "categories": "Seafood, Seafood Markets, Restaurants",
        "price_range": 3,
        "good_for_groups": False,
        "table_service": True,
        "takeout": True,
        "delivery": False,
        "ambiance_labels": ["casual", "classic"],
        "attributes": {"RestaurantsPriceRange2": "3"},
    },
    {
        "id": "sf-cha-cha-cha",
        "name": "Cha Cha Cha",
        "address": "1801 Haight St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94117",
        "latitude": 37.7690,
        "longitude": -122.4523,
        "stars": 4.2,
        "review_count": 2900,
        "categories": "Caribbean, Cuban, Tapas/Small Plates, Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["lively", "casual"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-senor-sisig",
        "name": "Senor Sisig",
        "address": "990 Valencia St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94110",
        "latitude": 37.7564,
        "longitude": -122.4210,
        "stars": 4.4,
        "review_count": 1800,
        "categories": "Filipino, Mexican, Asian Fusion, Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": False,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual", "trendy"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-shizen",
        "name": "Shizen Vegan Sushi Bar",
        "address": "370 14th St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94103",
        "latitude": 37.7683,
        "longitude": -122.4217,
        "stars": 4.6,
        "review_count": 2500,
        "categories": "Vegan, Vegetarian, Japanese, Sushi Bars, Restaurants",
        "price_range": 3,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["trendy", "classy"],
        "attributes": {"RestaurantsPriceRange2": "3"},
    },
    {
        "id": "sf-mandalay",
        "name": "Mandalay",
        "address": "4348 California St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94118",
        "latitude": 37.7849,
        "longitude": -122.4667,
        "stars": 4.4,
        "review_count": 1600,
        "categories": "Burmese, Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual", "classic"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-club-waziema",
        "name": "Club Waziema",
        "address": "543 Divisadero St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94117",
        "latitude": 37.7747,
        "longitude": -122.4377,
        "stars": 4.3,
        "review_count": 1200,
        "categories": "Ethiopian, African, Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual", "lively"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-golden-boy-pizza",
        "name": "Golden Boy Pizza",
        "address": "542 Green St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94133",
        "latitude": 37.7999,
        "longitude": -122.4085,
        "stars": 4.5,
        "review_count": 3500,
        "categories": "Pizza, Italian, Restaurants",
        "price_range": 1,
        "good_for_groups": True,
        "table_service": False,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual"],
        "attributes": {"RestaurantsPriceRange2": "1"},
    },
    {
        "id": "sf-tonys-pizza",
        "name": "Tony's Pizza Napoletana",
        "address": "1570 Stockton St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94133",
        "latitude": 37.8003,
        "longitude": -122.4091,
        "stars": 4.4,
        "review_count": 6400,
        "categories": "Pizza, Italian, Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual", "lively"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-pizzeria-delfina",
        "name": "Pizzeria Delfina",
        "address": "3611 18th St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94110",
        "latitude": 37.7614,
        "longitude": -122.4245,
        "stars": 4.3,
        "review_count": 2900,
        "categories": "Pizza, Italian, Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual", "trendy"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-4505-burgers-bbq",
        "name": "4505 Burgers & BBQ",
        "address": "705 Divisadero St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94117",
        "latitude": 37.7766,
        "longitude": -122.4382,
        "stars": 4.2,
        "review_count": 2900,
        "categories": "Barbeque, Burgers, American (Traditional), Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": False,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual", "outdoor"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-memphis-minnies",
        "name": "Memphis Minnie's",
        "address": "576 Haight St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94117",
        "latitude": 37.7718,
        "longitude": -122.4308,
        "stars": 4.1,
        "review_count": 1600,
        "categories": "Barbeque, Smokehouse, Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": False,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-hardwood-bar-smokery",
        "name": "Hardwood Bar & Smokery",
        "address": "680 8th St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94103",
        "latitude": 37.7704,
        "longitude": -122.4056,
        "stars": 4.2,
        "review_count": 1000,
        "categories": "Barbeque, Smokehouse, Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual", "lively"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-absinthe",
        "name": "Absinthe Brasserie & Bar",
        "address": "398 Hayes St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94102",
        "latitude": 37.7775,
        "longitude": -122.4229,
        "stars": 4.3,
        "review_count": 2600,
        "categories": "French, Brasseries, Restaurants",
        "price_range": 3,
        "good_for_groups": True,
        "table_service": True,
        "takeout": False,
        "delivery": False,
        "ambiance_labels": ["classy", "romantic"],
        "attributes": {"RestaurantsPriceRange2": "3"},
    },
    {
        "id": "sf-lardoise",
        "name": "L'Ardoise Bistro",
        "address": "151 Noe St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94114",
        "latitude": 37.7666,
        "longitude": -122.4333,
        "stars": 4.6,
        "review_count": 1600,
        "categories": "French, Bistros, Restaurants",
        "price_range": 3,
        "good_for_groups": False,
        "table_service": True,
        "takeout": False,
        "delivery": False,
        "ambiance_labels": ["romantic", "classy"],
        "attributes": {"RestaurantsPriceRange2": "3"},
    },
    {
        "id": "sf-chapeau",
        "name": "Chapeau!",
        "address": "126 Clement St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94118",
        "latitude": 37.7831,
        "longitude": -122.4600,
        "stars": 4.6,
        "review_count": 1900,
        "categories": "French, Restaurants",
        "price_range": 3,
        "good_for_groups": True,
        "table_service": True,
        "takeout": False,
        "delivery": False,
        "ambiance_labels": ["romantic", "classic"],
        "attributes": {"RestaurantsPriceRange2": "3"},
    },
    {
        "id": "sf-lers-ros",
        "name": "Lers Ros",
        "address": "730 Larkin St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94109",
        "latitude": 37.7841,
        "longitude": -122.4174,
        "stars": 4.3,
        "review_count": 2400,
        "categories": "Thai, Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-kin-khao",
        "name": "Kin Khao",
        "address": "55 Cyril Magnin St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94102",
        "latitude": 37.7855,
        "longitude": -122.4087,
        "stars": 4.3,
        "review_count": 2100,
        "categories": "Thai, Restaurants",
        "price_range": 3,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["trendy", "classy"],
        "attributes": {"RestaurantsPriceRange2": "3"},
    },
    {
        "id": "sf-r-and-g-lounge",
        "name": "R&G Lounge",
        "address": "631 Kearny St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94108",
        "latitude": 37.7938,
        "longitude": -122.4049,
        "stars": 4.2,
        "review_count": 3900,
        "categories": "Chinese, Cantonese, Seafood, Restaurants",
        "price_range": 3,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["classic", "lively"],
        "attributes": {"RestaurantsPriceRange2": "3"},
    },
    {
        "id": "sf-dumpling-home",
        "name": "Dumpling Home",
        "address": "298 Gough St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94102",
        "latitude": 37.7767,
        "longitude": -122.4224,
        "stars": 4.5,
        "review_count": 1700,
        "categories": "Chinese, Dumplings, Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual", "trendy"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-turtle-tower",
        "name": "Turtle Tower",
        "address": "501 6th St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94103",
        "latitude": 37.7766,
        "longitude": -122.4031,
        "stars": 4.3,
        "review_count": 2100,
        "categories": "Vietnamese, Noodles, Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-saigon-sandwich",
        "name": "Saigon Sandwich",
        "address": "560 Larkin St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94102",
        "latitude": 37.7828,
        "longitude": -122.4177,
        "stars": 4.6,
        "review_count": 3400,
        "categories": "Vietnamese, Banh Mi, Sandwiches, Restaurants",
        "price_range": 1,
        "good_for_groups": False,
        "table_service": False,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual"],
        "attributes": {"RestaurantsPriceRange2": "1"},
    },
    {
        "id": "sf-san-ho-won",
        "name": "San Ho Won",
        "address": "2170 Bryant St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94110",
        "latitude": 37.7599,
        "longitude": -122.4096,
        "stars": 4.5,
        "review_count": 900,
        "categories": "Korean, Barbeque, Restaurants",
        "price_range": 3,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": False,
        "ambiance_labels": ["trendy", "classy"],
        "attributes": {"RestaurantsPriceRange2": "3"},
    },
    {
        "id": "sf-muguboka",
        "name": "Muguboka",
        "address": "401 Balboa St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94118",
        "latitude": 37.7770,
        "longitude": -122.4642,
        "stars": 4.4,
        "review_count": 1000,
        "categories": "Korean, Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-kokkari",
        "name": "Kokkari Estiatorio",
        "address": "200 Jackson St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94111",
        "latitude": 37.7966,
        "longitude": -122.3991,
        "stars": 4.6,
        "review_count": 5100,
        "categories": "Greek, Mediterranean, Restaurants",
        "price_range": 4,
        "good_for_groups": True,
        "table_service": True,
        "takeout": False,
        "delivery": False,
        "ambiance_labels": ["classy", "romantic"],
        "attributes": {"RestaurantsPriceRange2": "4"},
    },
    {
        "id": "sf-abaca",
        "name": "Abaca",
        "address": "2700 Jones St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94133",
        "latitude": 37.8063,
        "longitude": -122.4170,
        "stars": 4.4,
        "review_count": 900,
        "categories": "Filipino, Restaurants",
        "price_range": 3,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["trendy", "classy"],
        "attributes": {"RestaurantsPriceRange2": "3"},
    },
    {
        "id": "sf-tselogs",
        "name": "Tselogs",
        "address": "552 Jones St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94102",
        "latitude": 37.7867,
        "longitude": -122.4130,
        "stars": 4.3,
        "review_count": 1100,
        "categories": "Filipino, Breakfast & Brunch, Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": False,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-new-eritrea",
        "name": "New Eritrea Restaurant",
        "address": "907 Irving St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94122",
        "latitude": 37.7640,
        "longitude": -122.4682,
        "stars": 4.5,
        "review_count": 1200,
        "categories": "Ethiopian, Eritrean, African, Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual", "cozy"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-massawa",
        "name": "Massawa",
        "address": "1538 Haight St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94117",
        "latitude": 37.7697,
        "longitude": -122.4474,
        "stars": 4.4,
        "review_count": 900,
        "categories": "Ethiopian, Eritrean, African, Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-greens",
        "name": "Greens Restaurant",
        "address": "2 Marina Blvd",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94123",
        "latitude": 37.8068,
        "longitude": -122.4321,
        "stars": 4.4,
        "review_count": 2800,
        "categories": "Vegetarian, Vegan, American (New), Restaurants",
        "price_range": 3,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": False,
        "ambiance_labels": ["classy", "waterfront"],
        "attributes": {"RestaurantsPriceRange2": "3"},
    },
    {
        "id": "sf-wildseed",
        "name": "Wildseed",
        "address": "2000 Union St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94123",
        "latitude": 37.7976,
        "longitude": -122.4317,
        "stars": 4.4,
        "review_count": 1600,
        "categories": "Vegan, Vegetarian, American (New), Restaurants",
        "price_range": 3,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["trendy", "classy"],
        "attributes": {"RestaurantsPriceRange2": "3"},
    },
    {
        "id": "sf-arsicault",
        "name": "Arsicault Bakery",
        "address": "397 Arguello Blvd",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94118",
        "latitude": 37.7832,
        "longitude": -122.4590,
        "stars": 4.8,
        "review_count": 3300,
        "categories": "Bakeries, Coffee & Tea, Food",
        "price_range": 2,
        "good_for_groups": False,
        "table_service": False,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-media-noche",
        "name": "Media Noche",
        "address": "3465 19th St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94110",
        "latitude": 37.7603,
        "longitude": -122.4215,
        "stars": 4.3,
        "review_count": 1200,
        "categories": "Cuban, Sandwiches, Latin American, Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": False,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual", "colorful"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-el-nuevo-frutilandia",
        "name": "El Nuevo Frutilandia",
        "address": "3077 24th St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94110",
        "latitude": 37.7526,
        "longitude": -122.4132,
        "stars": 4.2,
        "review_count": 900,
        "categories": "Cuban, Puerto Rican, Caribbean, Latin American, Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual", "lively"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-parada-22",
        "name": "Parada 22",
        "address": "1805 Haight St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94117",
        "latitude": 37.7690,
        "longitude": -122.4521,
        "stars": 4.2,
        "review_count": 1400,
        "categories": "Puerto Rican, Caribbean, Latin American, Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual", "lively"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
    {
        "id": "sf-peaches-patties",
        "name": "Peaches Patties",
        "address": "331 Cortland Ave",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94110",
        "latitude": 37.7392,
        "longitude": -122.4170,
        "stars": 4.5,
        "review_count": 700,
        "categories": "Jamaican, Caribbean, Restaurants",
        "price_range": 1,
        "good_for_groups": True,
        "table_service": False,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["casual"],
        "attributes": {"RestaurantsPriceRange2": "1"},
    },
    {
        "id": "sf-burma-love",
        "name": "Burma Love",
        "address": "211 Valencia St",
        "city": "San Francisco",
        "state": "CA",
        "postal_code": "94103",
        "latitude": 37.7694,
        "longitude": -122.4224,
        "stars": 4.4,
        "review_count": 2600,
        "categories": "Burmese, Asian Fusion, Restaurants",
        "price_range": 2,
        "good_for_groups": True,
        "table_service": True,
        "takeout": True,
        "delivery": True,
        "ambiance_labels": ["trendy", "lively"],
        "attributes": {"RestaurantsPriceRange2": "2"},
    },
]

# Backward-compatible alias for older imports/tests.
DEMO_BAY_AREA_RESTAURANTS = DEMO_SAN_FRANCISCO_FOOD_SPOTS
